export const REGISTER_CHALLANGE_REQUEST = "REGISTER_CHALLANGE_REQUEST";
export const REGISTER_CHALLANGE_SUCCESS = "REGISTER_CHALLANGE_SUCCESS";
export const REGISTER_CHALLANGE_FAIL = "REGISTER_CHALLANGE_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

